replicaCount: 2
namespace: "production"

image:
  repository: bazarkinzakhar/k8s-project
  pullPolicy: IfNotPresent
  tag: "latest"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 80

networkPolicy:
  enabled: true
